sudo: false

language: go
go:
  - 1.6

before_install:
  - go get github.com/golang/lint/golint

install:
  - go get -t -v ./...

script:
  - OUT=`gofmt -l .`; if [ "$OUT" ]; then echo $OUT; exit 1; fi
  - OUT=`golint ./...`; if [ "$OUT" ]; then echo $OUT; exit 1; fi
  - go vet ./...
  - #go test -v -coverprofile=reports/cover.out -covermode=count

before_deploy:
  - ./release.sh

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
    - "releases/ferret-linux-amd64.zip"
    - "releases/ferret-darwin-amd64.zip"
    - "releases/ferret-windows-amd64.zip"
  skip_cleanup: true
  overwrite: false
  on:
    tags: true
    go: '1.6'