sudo: false

language: go
go:
  - 1.6
  - 1.7

install:
  - go get github.com/golang/lint/golint
  - go get github.com/rakyll/statik
  - go generate ./assets/
  - go get -t -v ./...

script:
  - ./test.sh

before_deploy:
  - ./release.sh

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
    - "releases/ferret-linux-amd64.zip"
    - "releases/ferret-darwin-amd64.zip"
    - "releases/ferret-windows-amd64.zip"
  skip_cleanup: true
  overwrite: false
  on:
    tags: true
    go: '1.6'